
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 30 14:30:57 BRT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Divisao = 32;
  public static final int Ler = 10;
  public static final int Retorna = 14;
  public static final int Caractere = 7;
  public static final int FechaCH = 28;
  public static final int Enquanto = 16;
  public static final int Double = 6;
  public static final int Literal = 44;
  public static final int AbreCO = 25;
  public static final int Id = 43;
  public static final int Inteiro = 5;
  public static final int Maior = 36;
  public static final int Diferente = 38;
  public static final int AbreCH = 27;
  public static final int Senao = 9;
  public static final int Menos = 30;
  public static final int Menor = 35;
  public static final int Equivalente = 22;
  public static final int Principal = 13;
  public static final int Porcentagem = 33;
  public static final int Para = 17;
  public static final int AbreP = 23;
  public static final int Float = 11;
  public static final int MenosMenos = 20;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int AspasD = 31;
  public static final int FechaP = 24;
  public static final int MaiorIgual = 39;
  public static final int Imprimir = 12;
  public static final int Pv = 42;
  public static final int Virgula = 41;
  public static final int Multiplicacao = 34;
  public static final int MenorIgual = 40;
  public static final int Hash = 2;
  public static final int Const = 4;
  public static final int Se = 8;
  public static final int Lib = 15;
  public static final int Mais = 29;
  public static final int MaisMais = 19;
  public static final int Uniao = 18;
  public static final int Numero = 45;
  public static final int Include = 3;
  public static final int Igual = 37;
  public static final int FechaCO = 26;
  public static final int Ou = 21;
}

