/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package codigo;

public enum Tokens {
    Linha,
    MaisMais,
    MenosMenos,
    Hash,
    Include,
    Const,
    Inteiro,
    Double,
    Caractere,
    Floar,
    Se,
    SeNao,
    Ler,
    Escrever,
    Float,
    Imprimir,
    Principal,
    Retorna,
    Lib,
    Enquanto,
    Para,
    Uniao,
    Ou,
    Equivalente,
    Underline,
    AbreP,
    FechaP,
    AbreCO,
    FechaCO,
    AbreCH,
    FechaCH,
    Mais,
    Menos,
    AspasS,
    AspasD,
    Divisao,
    Barra,
    Exclamacao,
    Porcentagem,
    Multiplicacao,
    Menor,
    Maior,
    Igual,
    QuebraL,
    QuebraC,
    Diferente,
    MaiorIgual,
    MenorIgual,
    Ponto,
    Virgula,
    Pv,
    Comercial,
    Id,
    ERROR,
    Literal,
    Numero
    
    

}